### PR TITLE
Support RSpec matchers as diffable

### PR DESCRIPTION
**Pull request by denyago**

### CODE REVIEW

**Comment by locochris** [comment]
Ahh nice @denyago work.  :star2: 

So this is to use the `description` or `failure_message` from RSpec matchers?

eg.
`puts DiffMatcher::difference(RSpec::Matchers::BuiltIn::BeWithin.new(5).of(10), 2)`
```
- expected 2 to be within 5 of 10+ 2
Where, - 1 missing, + 1 additional
```

instead of the current behaviour:
```
- #<RSpec::Matchers::BuiltIn::BeWithin:0x007fb8fa840b10 @delta=5, @expected=10, @tolerance=5, @unit="">+ 2
Where, - 1 missing, + 1 additional
```

And that'd encourage the use of writing RSpec matchers vs plain old procs (which also have that ugly `.to_s` representation in the matcher output).

(hmmm... shame that `to_s` doesn't just return `description` on an RSpec matcher - then it would have "just worked".)

**Comment by locochris** [comment]
moved this in to #6

**Comment by denyago** [comment]
It's a pleasure to use your gem :+1: 

Is it not too late to add a relevant README section? (created a separate PR for that - https://github.com/diff-matcher/diff_matcher/pull/7)

**Comment by denyago** [comment]
... not sure if RSpec matchers actually worked before this patch. I had to use workarounds with something like `class ProxyRSpecMatcher < Proc`. To make it behave like a Proc and return pretty failure message.

**Comment by locochris** [comment]
Ahh great thanx @denyago - just waiting for a travis green light then I'll merge it all in.
The proc workaround looks interesting, but I like this addition with the RSpec matchers better.  :+1:

If there's anything else you can think of to make it better, or better explain what it does, or how to use it, that would be great!

I haven't really bothered promoting this gem, so it hasn't had too many people having to actually try using it.
I'd be interested to see any real life examples you have and how you're using it.
(eg. if there's features you've missed that I haven't documented well enough for you to have realized they existed.)

**Pull request closed without merging**
